<?
$precio = "50 dólares";
if($domain_id == 1) $precio = "$678.60 MXN";
if($domain_id == 2) $precio = "45 USD";
if($domain_id == 3) $precio = "36 Euros";
?>
<div style="margin:0 auto 0 auto;width:950px;overflow:hidden; padding-bottom:30px; padding-top:20px;">
<strong><span style="color:#000;">Servidores Dedicados</span></strong>

<p>Actualmente, nuestros clientes que poseen servidores dedicados o quienes han adquirido con HostDime.com.mx S.A de C.V el servicio de colocaci&oacute;n, el uso y consumo del Ancho de Banda (Bandwidth) es medido y facturado a escala Mbit/s en la norma de facturaci&oacute;n 95% Percentil.</p>
<p>HostDime.com.mx S.A de C.V considera que esta escala de facturaci&oacute;n (95% Percentil) es la m&aacute;s justa para el cliente asi como para el proveedor de hosting, por tal motivo este m&eacute;todo de facturaci&oacute;n es el que actualmente mejor se adapta y este implementamos para nuestros servicios de servidores dedicados y paquetes de colocaci&oacute;n. Nos hemos percatado que existe una fuerte confusi&oacute;n en nuestra clientela que proviene de nuestras practicas de ofrecer cuotas de ancho de banda en formato GB (gigabyte), pero nuestro m&eacute;todo de facturaci&oacute;n se realiza en Mbit utilizando el c&aacute;lculo del 95% Percentil. El objetivo de este art&iacute;culo es clarificar la interpretaci&oacute;n del como se factura el Ancho de Banda para nuestros clientes en base a Mbit  utilizando el calculo del 95%percentil.</p>
<p>Todos nuestros servidores dedicados y de colocaci&oacute;n, dependiendo de cu&aacute;l es el paquete que el cliente haya adquirido, se conecta a un puerto de 10Mbit o 100Mbit de conectividad de enlace ascendente. La mayor&iacute;a de los usuarios finales est&aacute;n familiarizados con el pago de servicios de telecomunicaci&oacute;n basados en unidades de consumo o bien el tiempo de uso del servicio contratado, sin embargo, la norma  de facturaci&oacute;n 95% Percentil no sigue este procedimiento. A medida que contin&uacute;e leyendo este art&iacute;culo, usted podr&aacute; ver c&oacute;mo es que el m&eacute;todo de facturaci&oacute;n es ben&eacute;fico para los clientes en comparaci&oacute;n con la facturaci&oacute;n de uso en Giga Bytes (GB) que se basa en la transferencia total durante el mes. La facturaci&oacute;n GB es recomendada para usuarios de empresa que tienen niveles m&aacute;s altos de uso. La norma percentil 95 toma muestras del consumo de ancho de banda y luego pasa por alto las muestras del 5% superior, en otras palabras, la norma NO toma en cuenta el 5% de los picos de utilizaci&oacute;n de ancho de banda para efectos de facturaci&oacute;n.</p>
<p>El consumo de ancho de banda es un valor calculado. Como hab&iacute;amos mencionado, cada servidor alojado es conectado a un puerto de 100Mbit o 10Mbit. Nuestro Sistema Verificador de Consumo de Ancho de Banda toma lectura del consumo de su servidor (tanto de entrada como de salida) en intervalos de 5 minutos a nivel de puerto y recoge dichos datos como una &quot;muestra&quot;. Esta &quot;muestra&quot; se almacena en una base de datos para realizar el c&aacute;lculo de uso posteriormente. Las muestras que se toman son proporcionados por la red, en bytes, y luego se traducen en kilobytes (1024 bytes) y posteriormente a megabytes (1024 kilobytes) para una interpretaci&oacute;n m&aacute;s precisa. La cifra de megabytes, una vez traducida, se divide por el n&uacute;mero de segundos que han pasado mientras se realizo la recolecci&oacute;n de la muestra (esto significa el n&uacute;mero de segundos en 5 minutos = 300 segundos) para encontrar la cantidad total de ancho de banda que ha entrado y salido de su servidor durante ese lapso de tiempo. </p>
<p>En este punto, las muestras de las lecturas realizadas se han traducido en Valores de Rendimiento tambi&eacute;n conocidos como megabytes por segundo, o Mbps (Mb). los valores de rendimiento de las muestras correspondientes se almacenan en una base de datos y se representan en una gr&aacute;fica para su uso posterior. Al final de cada mes, los valores de rendimiento de la muestra, son todas organizadas, listadas y ordenadas de mayor a menor de tal manera que una vez ordenadas la muestras, el 5% de las lecturas mas altas es eliminado, esto se lleva a cabo para conseguir &quot;la lectura de uso '95 %  Percentil.  A diferencia de otros m&eacute;todos de facturaci&oacute;n donde facturamos meses de 30 d&iacute;as, sin importar cu&aacute;ntos d&iacute;as posea realmente el mes, nuestro sistema de facturaci&oacute;n de ancho de banda utiliza meses con cifras reales es decir: 30 d&iacute;as en septiembre o 31 d&iacute;as en marzo.</p>
<p>&iquest;Qu&eacute; significa todo esto? Bueno, ya que nosotros almacenamos las muestras de uso de su servidor en intervalos de 5 minutos, somos capaces de promediar los totales y despu&eacute;s el resultado mostrarlo en el gr&aacute;fico de uso (que aparecen en Mbit y accesible a trav&eacute;s de su cuenta de CORE www.core.hostdime.com.mx). En el transcurso del mes, continuaremos realizando las muestras en intervalos de 5 minutos para promediar el consumo de Ancho de Banda, esto nos generara cerca de 8,640 muestras, las cuales usted vera reflejadas en as grafica Diaria de Bandwidth en el CORE. Estas 8,640 muestras, son organizadas de mayor a menor y tomamos el 5% de las muestras con mayor  consumo (432 muestras) y son eliminadas. Su consumo de Ancho de Banda es tomado a partir de la muestra mas alta despu&eacute;s de haber eliminado el 5% mas alto, en otras palabras, su consumo es considerado, a partir de la muestra mas alta del 95% de las muestras restantes. Si su consumo de Ancho de Banda es igual o inferior al estipulado en su servicio DESPU&Eacute;S de haber eliminado el 5% mas alto, no recibir&aacute; ning&uacute;n tipo de cargo adicional.</p>
<br />
<h2>Gr&aacute;fica</h2>
<p>Cualquier uso por encima del l&iacute;mite asignado de su cuenta se le cobrar&aacute;  la tasa apropiada de 
  <b><?=$precio;?></b> por Mbit extra consumido.</p>
  <div style="text-align:center">
    <a href="http://hostdime.com.mx/images/GraficaAnchoDeBanda.jpg" target="_blank"><img src="http://hostdime.com.mx/images/GraficaAnchoDeBanda.jpg" alt="" width="429" height="116" /></a> <br />
    [Haga Clic en la Imagen para ver más Grande ]
  </div>
<p>&iquest;Por qu&eacute; es esto ben&eacute;fico para usted? Bueno, como muchos de los sitios web de hoy en d&iacute;a tienen patrones irregulares de tr&aacute;fico, medir el consumo de ancho de banda en Mbps es el m&eacute;todo que m&aacute;s libera y excluye al cliente del pago de los aumentos repentinos de consumo(picos).  Como se mencion&oacute;, se toma el total de todas las muestras realizadas durante el mes de su servidor y se eliminan por completo la parte superior del 5% de las muestras. Esto es perfecto para aquellos clientes que operan sitios tales como, blogs, sitios de comercio electr&oacute;nico, peri&oacute;dicos, entre otros. Sabemos que un blog popular, la liberaci&oacute;n de nuevos productos, etc. Pueden dispararse los accesos o visitas a su servidor. Somos conscientes de esto y no consideramos que usted deba ser penalizado por los picos breves de acceso a su servidor o visitas a sus sitios web. </p>
<p>Medición de GB y su equivalente en Mbit<br />
  1,000 GB ~ 3.0 Mbit <br />
  1,500 GB ~ 4.5 Mbit<br />
  2,000 GB ~ 6.0 Mbit<br />
  3,000 GB ~ 10.0 Mbit<br />
  5,000 GB ~ 15.0 Mbit<br />
  10,000 GB ~ 30.0 Mbit<br />
  20,000 GB ~ 60.0 Mbit<br />
  <br />
  1 Mbit/s es aproximadamente equivalente a 325GB de uso sostenido durante un período de 30 días.<br />
  Si usted posee cualquier pregunta, duda o comentario referente a este tema, favor de ponerse en contacto vía Live Chat en nuestro sitio web www.hostdime.com.mx o bien vía Telefónica.</p>
</div>
