<div style="font-size:22px; color:#F60;text-shadow: 0 1px 0 #EAEAEA; height:27px;margin-top:10px; border-bottom:solid 1px #CCC; padding-bottom:5px;">Políticas de privacidad</div>
 <div style="padding:10px; margin-top:10px;">
  1. HostDime.com.mx S.A de C.V. se compromete a asegurar la confidencialidad/privacidad de la información personal obtenida a través de sus servicios en línea. Le sugerimos leer la normativa descrita a continuación, para entender el tratamiento de su información personal cuando utiliza nuestros servicios en el sitio de http://www.hostdime.com.mx. Estas normas de confidencialidad pueden tener cambios en el futuro, por lo que se recomienda revisarlas periódicamente. </section>
<p><strong style="color:#000;">1.1. Tipo de información personal que se obtiene.</strong>
  <section> En HostDime.com.mx S.A de C.V. recogemos información de diferentes maneras desde varias áreas de nuestro sitio web. Se encuentra sujeta a las normas de confidencialidad y privacidad toda aquella información personal que el usuario ingresa voluntariamente a nuestro sitio, la creación del perfil personal, la inscripción al servicio de notificación de ofertas especiales a través de correo electrónico, el registro a nuestros programas de lealtad, el envío de postales electrónicas, así como la información que ingresa durante su participación en los concursos, rifas y encuestas en línea que llevamos a cabo ocasionalmente. Para cada uno de estos programas, la información que se solicita es distinta y se almacena en bases de datos separadas. </section>
  <section> Contacto en línea: la información solicitada en esta sección permite a HostDime.com.mx S.A de C.V. contactar a los clientes cuando sea necesario. Entre la información solicitada al usuario se encuentra: nombre, apellido, nombre de la compañía donde trabaja, dirección, dirección de correo electrónico y número telefónico. </section>
  <section> Los usuarios pueden ser contactados por teléfono, correo o correo electrónico si se requiriera información adicional para completar alguna transacción. Programa de notificación de ofertas a través de correo electrónico. La información que los visitantes nos proporcionan incluye: nombre, apellido, dirección de correo electrónico, dirección, país, número de teléfono, preferencias y hábitos, entre otros. El usuario puede modificar esta información en cualquier momento y será empleada para adecuar las promociones y avisos enviados a las preferencias indicadas por él mismo. </section>
  <section> Envío de postales electrónicas. La información que los visitantes nos proporcionan incluye: nombre del remitente, dirección de correo electrónico del remitente, nombre del destinatario, dirección de correo electrónico del destinatario, rango de edad, país, sexo y código postal. Esta información será empleada para adecuar las promociones y avisos enviados al cliente. </section>
  <section> Concursos, rifas y encuestas en línea: El tipo de información solicitada por estos medios puede ser muy variable, podrá incluir datos personales, hábitos y preferencias, opiniones acerca de los servicios de nuestros sitios y comentarios acerca de servicios propuestos. La información recabada será para uso exclusivo de HostDime.com.mx S.A de C.V. y tendrá como finalidad la retroalimentación de los usuarios acerca de los servicios que prestamos con el fin de mejorarlos. </section>
  <section> Después de que la información llega a HostDime.com.mx S.A de C.V., ésta es almacenada en un servidor seguro que reside atrás de un firewall diseñado para obstaculizar el acceso desde afuera de la compañía. Desafortunadamente, ninguna transmisión por Internet puede garantizar su seguridad al 100%. Por lo tanto, aunque HostDime.com.mx S.A de C.V. se esfuerce en proteger su información personal, no puede asegurar ni garantizar la seguridad en la transmisión de ninguna información relacionada con ninguno de nuestros servicios en línea, por lo que usted corre su propio riesgo. Una vez recibidos los datos, haremos todo lo posible para salvaguardar su seguridad en nuestros sistemas. En este tema, el equipo de colaboradores de HostDime.com.mx S.A de C.V. ha enfocado sus esfuerzos para ofrecer la tecnología más moderna y actualizada a fin de ofrecerle la mayor seguridad posible. </section>
</p>
<p><strong style="color:#000;">1.2. Cómo se utiliza su información personal </strong>
  <section> HostDime.com.mx S.A de C.V. utiliza la información suministrada durante el proceso de registro de perfil, inscripción a algún programa y promociones para realizar estudios internos sobre los datos demográficos, intereses y comportamiento de nuestros usuarios -este estudio se compila y analiza en conjunto. El objetivo más importante de HostDime.com.mx S.A de C.V. al recoger datos personales es entender y proporcionar al usuario una experiencia más satisfactoria al visitar nuestros sitios y adquirir nuestros servicios, ya que al conocer más a nuestros visitantes podemos proporcionarles productos acordes a sus necesidades, así como contenido y publicidad más adecuados. </section>
  <section> Al recabar los datos del usuario en línea, podemos elaborar estadísticas internas que nos indiquen cuáles son los servicios y productos más apreciados por diferentes segmentos de usuarios, igualmente nos sirve para dar la formalidad debida al proceso transaccional. </section>
  <section> En nuestro programa de notificación de ofertas a través de correo electrónico, sólo HostDime.com.mx S.A de C.V. tiene acceso a la información recabada. Este tipo de publicidad se realiza mediante avisos y mensajes promocionales de correo electrónico, los cuales sólo serán enviados a usted, si al momento de registrarse usted indicó que desearía recibirlos, esta indicación podrá usted modificarla en cualquier momento. En los correos electrónicos enviados, pueden incluirse ocasionalmente ofertas de terceras partes que sean nuestros socios comerciales. </section>
  <section> Además de solicitar información durante los procesos de registro antes mencionados, le podremos solicitar información personal en otras ocasiones como, por ejemplo, al participar en un concurso o en cualquier promoción de nuestro sitio y al notificarnos sobre un problema con nuestro sitio o servicios. HostDime.com.mx S.A de C.V. también suele hacer encuestas entre sus usuarios en línea, cuyas respuestas son utilizadas en estudios internos. </section>
</p>
<p><strong style="color:#000;">1.3. Qué son los cookies y cómo se utilizan.</strong>
  <section> Los cookies son pequeñas piezas de información que son enviadas por el sitio Web a su navegador. 
    Los cookies se almacenan en el disco duro de su equipo y se utilizan para determinar sus preferencias cuando se conecta a los servicios de nuestros sitios, así como para rastrear determinados comportamientos o actividades llevadas a cabo por usted dentro de nuestros sitios. </section>
  <section> En algunas secciones de nuestro sitio requerimos que el cliente tenga habilitados los cookies ya que algunas de las funcionalidades requieren de éstas para trabajar. Los cookies nos permiten: a) reconocerlo al momento de entrar a nuestros sitios y ofrecerle de una experiencia personalizada, b) conocer la configuración personal del sitio especificada por usted, por ejemplo, los cookies nos pemiten detectar el ancho de banda que usted ha seleccionado al momento de ingresar al home page de nuestros sitios, de tal forma que sabemos qué tipo de información es aconsejable descargar, c) calcular el tamaño de nuestra audiencia y medir algunos parámetros de tráfico, pues cada navegador que obtiene acceso a nuestros sitios adquiere un cookie que se usa para determinar la frecuencia de uso y las secciones de los sitios visitadas, reflejando así sus hábitos y preferencias, información que nos es útil para mejorar el contenido, los titulares y las promociones para los usuarios. Los cookies también nos ayudan a rastrear algunas actividades, por ejemplo, en algunas de las encuestas que lanzamos en línea, podemos utilizar cookies para detectar si el usuario ya ha llenado la encuesta y evitar desplegarla nuevamente, en caso de que lo haya hecho. El botón de "ayuda" que se encuentra en la barra de herramientas de la mayoría de los navegadores, le dirá cómo evitar aceptar nuevos cookies, cómo hacer que el navegador le notifique cuando recibe un nuevo cookie o cómo deshabilitar todos los cookies. Sin embargo, las cookies le permitirán tomar ventaja de las características más benéficas que le ofrecemos, por lo que le recomendamos que las deje activadas. </section>
</p>
<p><strong style="color:#000;">1.4. Confidencialidad de la información</strong>
  <section> Cuando se encuentre en el sitio de HostDime.com.mx S.A de C.V. y le pidan datos personales, usted compartirá la información sólo con HostDime.com.mx S.A de C.V, salvo que se especifique lo contrario. </section>
  <section> HostDime.com.mx S.A de C.V. no compartirá la información confidencial con terceras partes, excepto que tenga expresa autorización de quienes se suscribieron, o cuando haya sido requerido por orden judicial para cumplir con las disposiciones procesales. </section>
  <section> HostDime.com.mx S.A de C.V. no vende ni alquila la información de los usuarios. Si los datos personales del usuario debieran ser compartidos con socios comerciales o patrocinantes, el usuario será notificado antes que éstos sean recogidos o transferidos. Si el usuario no desea que sus datos sean compartidos, puede decidir no utilizar un servicio determinado o no participar en algunas promociones o concursos. </section>
  <section> HostDime.com.mx S.A de C.V. puede difundir las estadísticas en conjunto de los usuarios (por ejemplo, el porcentaje de nuestros usuarios que son hombres o mayores a determinada edad, etc.) para describir nuestros servicios y para otros propósitos lícitos en los casos que marque la ley. </section>
  <section> HostDime.com.mx S.A de C.V. puede difundir la información de la cuenta en casos especiales cuando pensemos que proporcionar esta información puede servir para identificar, localizar o realizar acciones legales contra personas que pudiesen infringir las condiciones del servicio del sitios de HostDime.com.mx S.A de C.V., o causar daños o interferencia sobre los derechos de HostDime.com.mx S.A de C.V. o sus propiedades, de otros usuarios del sitios de HostDime.com.mx S.A de C.V. o de cualquier otra persona que pudiese resultar perjudicada por dichas actividades. HostDime.com.mx S.A de C.V. puede difundir u obtener acceso a la información de cuenta cuando, actuando de buena fé, creamos que es necesario por razones legales, administrativas o de otra índole y lo consideremos necesario para mantener, proporcionar y desarrollar nuestros productos y servicios. </section>
  <section> HostDime.com.mx S.A de C.V. no asume ninguna obligación de mantener confidencial cualquier otra información que el usuario proporcione, incluyendo aquella información que el usuario proporcione a través de boletines y pláticas en línea (chats), así como la información que obtenga a través de los cookies que se describen en el inciso 3, lo anterior en términos de lo establecido en el artículo 109 de la Ley Federal de los Derechos de Autor y de la fracción I, del artículo 76 bis de la Ley Federal de Protección al Consumidor. </section>
</p>
<p><strong style="color:#000;">1</strong><strong style="color:#000;">.5. Modificación / actualización de la información.</strong>
  <section> Los datos personales proporcionados por el usuario formarán parte de un archivo que contendrá su perfil. El usuario puede modificar su perfil en cualquier momento utilizando su número de usuario/socio y su número de identificación personal asignados o que él mismo eligió. </section>
  <section> HostDime.com.mx S.A de C.V. aconseja al usuario que actualice sus datos cada vez que éstos sufran alguna modificación, ya que esto permitirá brindarle un servicio más personalizado. </section>
  <section> Si usted participa en el servicio de promociones vía correo electrónico podrá en cualquier momento desactivar el servicio. </section>
</p>
<p><strong style="color:#000;">1.6. Protección de la información personal</strong>
  <section> La información proporcionada por el usuario, está asegurada por un número de identificación personal al cual sólo el usuario podrá acceder y de la cual sólo él tiene conocimiento. </section>
  <section> Le recomendamos que no revele su contraseña a nadie. HostDime.com.mx S.A de C.V. no solicitará su contraseña en ninguna llamada telefónica o mensaje de correo no solicitados. En todo momento, el usuario es el responsable único y final de mantener en secreto su número de usuario / socio, contraseña personal, clave de acceso y número confidencial con los cuales tenga acceso a los servicios y contenidos de nuestro sitio. Para disminuir los riesgos HostDime.com.mx S.A de C.V. recomienda al usuario salir de su cuenta y cerrar la ventana de su navegador cuando finalice su actividad, más aún si comparte su computadora con alguien o utiliza una computadora en un lugar público como una biblioteca o un café Internet. </section>
  <section> Una vez recibidos los datos, haremos todo lo posible para salvaguardar su seguridad en nuestros sistemas. En este tema, el equipo de colaboradores de HostDime.com.mx S.A de C.V. ha enfocado sus esfuerzos para ofrecer la tecnología más moderna y actualizada a fin de ofrecerle la mayor seguridad posible. </section>
</p>
<p><strong style="color:#000;">1.7. Confidencialidad de los menores.</strong>
  <section> La salvaguarda de la información personal infantil es extremadamente importante. HostDime.com.mx S.A de C.V. recauda el mínimo indispensable de esa información necesaria para brindar sus servicios. </section>
  <section> HostDime.com.mx S.A de C.V. no solicita información de identificación personal a los menores. Los menores siempre deben solicitar permiso a sus padres antes de enviar información personal a otro usuario que se encuentre en línea. </section>
</p>
<p><strong style="color:#000;">1.8. Aceptación de los términos.</strong>
  <section> Esta declaración de Confidencialidad / Privacidad está sujeta a los términos y condiciones de HostDime.com.mx S.A de C.V. lo cual constituye un acuerdo legal entre el usuario y HostDime.com.mx S.A de C.V. </section>
  <section> Si el usuario utiliza los servicios de HostDime.com.mx S.A de C.V. en cualquiera de sus sitios, significa que ha leído, entendido y acordado los términos antes expuestos. Si no está de acuerdo con ellos, el usuario no deberá proporcionar ninguna información personal, ni utilizar los servicios de los sitios de HostDime.com.mx S.A de C.V. </section>
</p>
<p><strong style="color:#000;">1.9.- Principios mínimos de nuestra política de privacidad / confidencialidad </strong>
  <section> A continuación, HostDime.com.mx S.A de C.V. le expondrá brevemente los principios que rigen sus políticas de privacidad y confidencialidad para la información proporcionada por los usuarios de sus servicios electrónicos en línea: </section>
</p>
<ul style="list-style-type: upper-roman;">
  <li>HostDime.com.mx S.A de C.V. únicamente recabara la información del cliente que es necesaria para brindarle los servicios personalizados que se encuentran disponibles en sus sitios en Internet, la cual se utilizará únicamente para los fines que es solicitada. </li>
  <li>HostDime.com.mx S.A de C.V. se esfuerza por asegurar la calidad de la información que se recaba sobre nuestros usuarios de servicios en línea, particularmente cuando se haya obtenido al través de algún proveedor de información o de servicios. </li>
  <li>HostDime.com.mx S.A de C.V. enfoca sus esfuerzos para ofrecer la tecnología más moderna y actualizada a fin de ofrecer a sus clientes/usuarios la mayor seguridad posible en el manejo y transferencia de la información que es requerida en los diversos procesos de requerimiento de datos. </li>
  <li>HostDime.com.mx S.A de C.V. evita la divulgación de información acerca del cliente/usuario, haciéndolo únicamente respecto de aquellos datos que expresamente sean autorizados para ello. </li>
  <li>En todo momento, HostDime.com.mx S.A de C.V. está atento a las inquietudes que manifiesten nuestros clientes/usuarios respecto al manejo de la información que proporcionen para los diversos procesos en línea. </li>
  <li>HostDime.com.mx S.A de C.V. cuida de que estos principios de privacidad/confidencialidad se extiendan al conjunto de relaciones comerciales al interior del grupo. </li>
  <li>HostDime.com.mx S.A de C.V. comparte la responsabilidad del cuidado de la información con sus empleados, haciéndolos copartícipes de los lineamientos expuestos en los documentos de "Políticas de privacidad/confidencialidad". </li>
</ul>
</div>